version: '2'
networks: 
    gnode:

services:
    node-app:
        build: node
        networks: 
            - gnode
        ports:
            - "3000:3000"
        volumes:
            - $PWD/node:/home/data

    nginx:
        build: nginx
        networks: 
            - gnode
        depends_on:
            - node-app
        ports:
            - '80:80'
        volumes:
            - $PWD/nginx:/etc/nginx